name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose Terraform action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
    
env:
  AWS_REGION : us-east-1 

permissions:
      id-token: write   
      contents: read
 
jobs:
#   AssumeRoleAndCallIdentity:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Git clone the repository
#         uses: actions/checkout@v3
#       - name: configure aws credentials
#         uses: aws-actions/configure-aws-credentials@v1.7.0
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#           role-session-name: GitHub_to_AWS_via_FederatedOIDC
#           aws-region: ${{ env.AWS_REGION }}
#       - name: Sts GetCallerIdentity
#         run: |
#           aws sts get-caller-identity
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Repository'
      uses: actions/checkout@v2

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0
    - name: 'cd to 01.vpc'
      run: cd 01.vpc

    - name: 'listing content in the folder'
      run: ls -l

    # - name: 'Terraform Init'
    #   run: terraform init -upgrade

    # - name: 'Terraform Format'
    #   run: terraform fmt -check

    # - name: 'Terraform Validate'
    #   run: terraform validate

    # - name: 'Terraform Plan'
    #   run: terraform plan

    # - name: 'Terraform Apply or Destroy'
    #   run: terraform ${{ github.event.inputs.action }} -auto-approve
      

