name: Terraform Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action: apply or destroy'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

env:
  AWS_REGION: us-east-1
  TF_VERSION: '1.8.5'
  TF_WORKING_DIR: '01.vpc'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Get Caller Identity
        run: aws sts get-caller-identity

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Initializing
        run: terraform init -upgrade
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=plan.tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload Plan
        uses: actions/upload-artifact@v2
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/plan.tfplan

  approval:
    name: 'Approve Terraform Action'
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Download Plan
        uses: actions/download-artifact@v2
        with:
          name: terraform-plan
          path: plan.tfplan

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Execute Terraform Action
        if: github.event.inputs.action == 'apply' || github.event.inputs.action == 'destroy'
        run: |
          if [ "${{ github.event.inputs.action }}" == "apply" ]; then
            terraform apply "plan.tfplan"
          elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
            terraform destroy -auto-approve
          else
            echo "Invalid action provided: ${{ github.event.inputs.action }}. Exiting."
            exit 1
        working-directory: ${{ env.TF_WORKING_DIR }}
